/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentSlugRouteImport } from './routes/assessment.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMandatesIndexRouteImport } from './routes/_authenticated/mandates.index'
import { Route as AuthenticatedMandatesIdRouteImport } from './routes/_authenticated/mandates.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentSlugRoute = AssessmentSlugRouteImport.update({
  id: '/assessment/$slug',
  path: '/assessment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMandatesIndexRoute =
  AuthenticatedMandatesIndexRouteImport.update({
    id: '/mandates/',
    path: '/mandates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMandatesIdRoute = AuthenticatedMandatesIdRouteImport.update({
  id: '/mandates/$id',
  path: '/mandates/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/mandates/$id': typeof AuthenticatedMandatesIdRoute
  '/mandates/': typeof AuthenticatedMandatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/mandates/$id': typeof AuthenticatedMandatesIdRoute
  '/mandates': typeof AuthenticatedMandatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/assessment/$slug': typeof AssessmentSlugRoute
  '/_authenticated/mandates/$id': typeof AuthenticatedMandatesIdRoute
  '/_authenticated/mandates/': typeof AuthenticatedMandatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assessment/$slug'
    | '/mandates/$id'
    | '/mandates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assessment/$slug'
    | '/mandates/$id'
    | '/mandates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/assessment/$slug'
    | '/_authenticated/mandates/$id'
    | '/_authenticated/mandates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AssessmentSlugRoute: typeof AssessmentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$slug': {
      id: '/assessment/$slug'
      path: '/assessment/$slug'
      fullPath: '/assessment/$slug'
      preLoaderRoute: typeof AssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mandates/': {
      id: '/_authenticated/mandates/'
      path: '/mandates'
      fullPath: '/mandates/'
      preLoaderRoute: typeof AuthenticatedMandatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mandates/$id': {
      id: '/_authenticated/mandates/$id'
      path: '/mandates/$id'
      fullPath: '/mandates/$id'
      preLoaderRoute: typeof AuthenticatedMandatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMandatesIdRoute: typeof AuthenticatedMandatesIdRoute
  AuthenticatedMandatesIndexRoute: typeof AuthenticatedMandatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMandatesIdRoute: AuthenticatedMandatesIdRoute,
  AuthenticatedMandatesIndexRoute: AuthenticatedMandatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AssessmentSlugRoute: AssessmentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
